globals
//globals from INITVJEXECLUAAPP:
constant boolean LIBRARY_INITVJEXECLUAAPP=true
//endglobals from INITVJEXECLUAAPP
    // Generated
trigger gg_trg_solareditr= null

trigger l__library_init

//JASSHelper struct globals:

//JASSHelper null local generated globals:

    // User-defined
    location                udg_triunitloc             = null
    location                udg_tarloc                 = null
    location                udg_loc                    = null
    destructable array      udg_dummy

    // Generated
    trigger                 gg_trg________________u    = null
    trigger                 gg_trg_gouhe               = null
endglobals


//library INITVJEXECLUAAPP:
    function INITVJEXECLUAAPP__init_function takes nothing returns nothing
        call Cheat("exec-lua: solar_boot")
    endfunction 

//library INITVJEXECLUAAPP ends
//===========================================================================
// 
// 只是另外一张魔兽争霸III的地图
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Wed Sep 24 23:14:33 2025
//   Map Author: 未知的
// 
//===========================================================================
//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************
function InitGlobals takes nothing returns nothing
endfunction
//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************
//--------call Cheat("exec-lua: solar_boot")-------------
//------------------------------------------------

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

function checkX takes real x returns real       //判断X坐标是否出界,出界返回边界值
local real r=GetRectMinX(bj_mapInitialPlayableArea)+50
if(x<r)then
return r
endif
set r=GetRectMaxX(bj_mapInitialPlayableArea)-50
if(x>r)then
return r
endif
return x
endfunction
function checkY takes real y returns real       //判断Y坐标是否出界,出界返回边界值
local real r=GetRectMinY(bj_mapInitialPlayableArea)+50
if(y<r)then
return r
endif
set r=GetRectMaxY(bj_mapInitialPlayableArea)-50
if(y>r)then
return r
endif
return y
endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************
//===========================================================================
// Trigger: solareditr
//===========================================================================
function Trig_solareditrActions takes nothing returns nothing
endfunction
//===========================================================================
function InitTrig_solareditr takes nothing returns nothing
    set gg_trg_solareditr=CreateTrigger()
    call TriggerAddAction(gg_trg_solareditr, function Trig_solareditrActions)
endfunction

//===========================================================================
// Trigger: gouhe
//===========================================================================
function Trig_gouhe_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A000' ) ) then
        return false
    endif
    return true
endfunction

function Trig_gouhe_Actions takes nothing returns nothing
    set udg_tarloc = GetSpellTargetLoc()
    set udg_triunitloc = GetUnitLoc(GetTriggerUnit())
    set bj_forLoopAIndex = 1
    set bj_forLoopAIndexEnd = 20
    loop
        exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
        set udg_loc = PolarProjectionBJ(udg_triunitloc, I2R(( GetForLoopIndexA() * 60 )), AngleBetweenPoints(udg_triunitloc, udg_tarloc))
        call MoveLocation(udg_loc,checkX(GetLocationX(udg_loc)),checkY(GetLocationY(udg_loc)))
        // 此处JASS为判断边界,超出边界使udg_loc为边界值,新手可不用
        call CreateDestructableLoc( 'B000', udg_loc, GetRandomReal(0.00, 360.00), 0.50, GetRandomInt(0, 2) )
        set udg_dummy[GetForLoopIndexA()] = GetLastCreatedDestructable()
        call AddSpecialEffectLocBJ( udg_loc, "Abilities\\Spells\\Other\\Volcano\\VolcanoDeath.mdl" )
        call DestroyEffectBJ( GetLastCreatedEffectBJ() )
        call RemoveLocation(udg_loc)
        set bj_forLoopAIndex = bj_forLoopAIndex + 1
    endloop
    call TriggerSleepAction( 8.00 )
    set bj_forLoopBIndex = 1
    set bj_forLoopBIndexEnd = 20
    loop
        exitwhen bj_forLoopBIndex > bj_forLoopBIndexEnd
        call RemoveDestructable( udg_dummy[GetForLoopIndexB()] )
        set bj_forLoopBIndex = bj_forLoopBIndex + 1
    endloop
    call RemoveLocation(udg_tarloc)
    call RemoveLocation(udg_triunitloc)
endfunction

//===========================================================================
function InitTrig_gouhe takes nothing returns nothing
    set gg_trg_gouhe = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_gouhe, EVENT_PLAYER_UNIT_SPELL_EFFECT )
    call TriggerAddCondition( gg_trg_gouhe, Condition( function Trig_gouhe_Conditions ) )
    call TriggerAddAction( gg_trg_gouhe, function Trig_gouhe_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_solareditr()
    call InitTrig_gouhe(  )
endfunction
//***************************************************************************
//*
//*  Players
//*
//***************************************************************************
function InitCustomPlayerSlots takes nothing returns nothing
    // Player 0
    call SetPlayerStartLocation(Player(0), 0)
    call SetPlayerColor(Player(0), ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(0), true)
    call SetPlayerController(Player(0), MAP_CONTROL_USER)
    // Player 1
    call SetPlayerStartLocation(Player(1), 1)
    call SetPlayerColor(Player(1), ConvertPlayerColor(1))
    call SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(1), true)
    call SetPlayerController(Player(1), MAP_CONTROL_USER)
    // Player 2
    call SetPlayerStartLocation(Player(2), 2)
    call SetPlayerColor(Player(2), ConvertPlayerColor(2))
    call SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(2), true)
    call SetPlayerController(Player(2), MAP_CONTROL_USER)
    // Player 3
    call SetPlayerStartLocation(Player(3), 3)
    call SetPlayerColor(Player(3), ConvertPlayerColor(3))
    call SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(3), true)
    call SetPlayerController(Player(3), MAP_CONTROL_USER)
    // Player 11
    call SetPlayerStartLocation(Player(11), 4)
    call SetPlayerColor(Player(11), ConvertPlayerColor(11))
    call SetPlayerRacePreference(Player(11), RACE_PREF_ORC)
    call SetPlayerRaceSelectable(Player(11), true)
    call SetPlayerController(Player(11), MAP_CONTROL_COMPUTER)
endfunction
function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam(Player(0), 0)
    call SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(1), 0)
    call SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(2), 0)
    call SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(3), 0)
    call SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    //   Allied
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    // Force: TRIGSTR_010
    call SetPlayerTeam(Player(11), 1)
    call SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
endfunction
function InitAllyPriorities takes nothing returns nothing
    call SetStartLocPrioCount(0, 2)
    call SetStartLocPrio(0, 0, 2, MAP_LOC_PRIO_LOW)
    call SetStartLocPrio(0, 1, 3, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(1, 3)
    call SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1, 2, 3, MAP_LOC_PRIO_LOW)
    call SetStartLocPrioCount(2, 1)
    call SetStartLocPrio(2, 0, 3, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(3, 1)
    call SetStartLocPrio(3, 0, 2, MAP_LOC_PRIO_HIGH)
endfunction
//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************
//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds(- 3840.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), - 4096.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3840.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3584.0 - GetCameraMargin(CAMERA_MARGIN_TOP), - 3840.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3584.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3840.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), - 4096.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    call NewSoundEnvironment("Default")
    call SetAmbientDaySound("LordaeronSummerDay")
    call SetAmbientNightSound("LordaeronSummerNight")
    call SetMapMusic("Music", true, 0)
    call InitBlizzard()

call ExecuteFunc("INITVJEXECLUAAPP__init_function")

    call InitGlobals()
    //call InitTrig_solareditr() // INLINED!!
    call InitCustomTriggers()
endfunction
//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************
function config takes nothing returns nothing
    call SetMapName("TRIGSTR_003")
    call SetMapDescription("TRIGSTR_005")
    call SetPlayers(5)
    call SetTeams(5)
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    call DefineStartLocation(0, - 320.0, - 192.0)
    call DefineStartLocation(1, - 3520.0, - 3840.0)
    call DefineStartLocation(2, 1984.0, - 1856.0)
    call DefineStartLocation(3, 1792.0, - 512.0)
    call DefineStartLocation(4, 1984.0, 64.0)
    // Player setup
    call InitCustomPlayerSlots()
    call InitCustomTeams()
    call InitAllyPriorities()
endfunction




//Struct method generated initializers/callers:

