//Generated By Solar Editor

import 单位自动创建系统 from "state/系统/单位自动创建系统"
/**
	id = id
	unitId = 创建单位id
	itemId = 创建物品id
	owner = 创建所属玩家
	loc = 创建位置(支持线变量)
	creationTime = 何时创建(不填为靠近时创建)
	count = 创建数量
	area = 分散范围
	reviveTime = 复活时间(不填不复活)
*/
export type data_type = {
	id?: string
	unitId?: string
	itemId?: any
	owner?: number
	loc?: any
	creationTime?: number
	count?: number
	area?: number
	reviveTime?: any
    [key:string]: any
}

declare global {
    type t_单位自动创建系统 = data_type
}

export const data: data_type[] = [
	{
		"id":"dwzdcjxt001",
		"unitId":"hfoo",
		"owner":11,
		"loc":{
			"x":100,
			"y":0
		},
		"creationTime":0.01,
		"count":1,
		"area":200
	},
	{
		"id":"au01",
		"unitId":"au01",
		"owner":11,
		"loc":{
			"x":100,
			"y":20
		},
		"creationTime":0.01,
		"count":1
	}
]
export const d_单位自动创建系统 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            单位自动创建系统.config.push(datum)
        }
    }
}
