//Generated By Solar Editor

import 选择英雄 from "script/选择英雄"
/**
	key_name = 配置项名字
	value = 值
	#<%1%># = 配置代码
*/
export type data_type = {
	key_name?: string
	value?: any
    [key:string]: any
}

declare global {
    type t_开局选择英雄角色 = data_type
}

export const data: data_type[] = [
	{
		"key_name":"备选项数量",
		"value":3,
		"#<%1%>#":"    开局选择英雄角色.cfg.optionSize = 3"
	},
	{
		"key_name":"默认可重随次数",
		"value":1,
		"#<%1%>#":"    开局选择英雄角色.cfg.freeRefreshCount = 1"
	}
]
export const d_开局选择英雄角色 = data;


//code
export default function(){

	    选择英雄.cfg.optionSize = 3
	    选择英雄.cfg.freeRefreshCount = 1
}
