//Generated By Solar Editor

import 技能书学习到QWER栏位 from "state/系统/技能书学习到QWER栏位"
import GradeUtil from "@/GradeUtil"
import DataBase from "@/DataBase"
/**
	id = id
	_parent = 父id
	baseName = 基础名字
	grade = 品级
	abilityId = 学习技能的id
	Name = 名字
	Description = 说明
	Art = 图标
	stockMax = 最大库存量
	stockRegen = 购买时间间隔
	stockStart = 购买开始时间
	abilList = 技能
	scale = 模型缩放
	file = 模型文件
	colorR = 红
	colorB = 蓝
	colorG = 绿
*/
export type data_type = {
	id?: string
	_parent?: string
	baseName?: string
	grade?: number
	abilityId?: string
	Name?: string
	Description?: string
	Art?: string
	stockMax?: any
	stockRegen?: any
	stockStart?: any
	abilList?: string
	scale?: number
	file?: string
	colorR?: number
	colorB?: number
	colorG?: number
    [key:string]: any
}

declare global {
    type t_技能书学习到QWER栏位 = data_type
}

export const data: data_type[] = [
	{
		"id":"ad7u",
		"_parent":"shea",
		"baseName":"召唤熊",
		"grade":1,
		"abilityId":"ANsw",
		"Name":"召唤熊【1级】",
		"Description":"点击使用学习召唤熊",
		"Art":"ReplaceableTextures\\CommandButtons\\BTNWarStomp.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":0,
		"colorB":0,
		"colorG":255,
		"Ubertip":"点击使用学习召唤熊",
		"Tip":"召唤熊【1级】"
	},
	{
		"id":"ad7v",
		"_parent":"shea",
		"baseName":"召唤熊",
		"grade":2,
		"abilityId":"ANsy",
		"Name":"召唤熊【2级】",
		"Description":"点击使用学习召唤熊",
		"Art":"ReplaceableTextures\\CommandButtons\\BTNWarStomp.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":0,
		"colorB":255,
		"colorG":0,
		"Ubertip":"点击使用学习召唤熊",
		"Tip":"召唤熊【2级】"
	},
	{
		"id":"ad7w",
		"_parent":"shea",
		"baseName":"召唤豪猪",
		"grade":1,
		"abilityId":"ANtm",
		"Name":"召唤豪猪【1级】",
		"Description":"点击使用学习召唤豪猪",
		"Art":"ReplaceableTextures\\CommandButtons\\BTNWarStomp.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"Ubertip":"点击使用学习召唤豪猪",
		"Tip":"召唤豪猪【1级】"
	},
	{
		"id":"ad7x",
		"_parent":"shea",
		"baseName":"召唤豪猪",
		"grade":2,
		"abilityId":"ANsq",
		"Name":"召唤豪猪【2级】",
		"Description":"点击使用学习召唤豪猪",
		"Art":"ReplaceableTextures\\CommandButtons\\BTNWarStomp.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":255,
		"colorB":0,
		"colorG":255,
		"Ubertip":"点击使用学习召唤豪猪",
		"Tip":"召唤豪猪【2级】"
	},
	{
		"id":"ad7y",
		"_parent":"shea",
		"baseName":"测试技能a",
		"grade":1,
		"abilityId":"ANsw",
		"Name":"测试技能a【1级】",
		"Description":"点击使用学习测试技能a",
		"Art":"ReplaceableTextures\\CommandButtons\\BTNWarStomp.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":255,
		"colorB":0,
		"colorG":0,
		"Ubertip":"点击使用学习测试技能a",
		"Tip":"测试技能a【1级】"
	},
	{
		"id":"ad7z",
		"_parent":"shea",
		"baseName":"测试技能a",
		"grade":2,
		"abilityId":"ANsy",
		"Name":"测试技能a【2级】",
		"Description":"点击使用学习测试技能a",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCriticalStrike.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":0,
		"colorB":0,
		"colorG":255,
		"Ubertip":"点击使用学习测试技能a",
		"Tip":"测试技能a【2级】"
	},
	{
		"id":"ad80",
		"_parent":"shea",
		"baseName":"测试技能b",
		"grade":1,
		"abilityId":"ANtm",
		"Name":"测试技能b【1级】",
		"Description":"点击使用学习测试技能b",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCriticalStrike.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":0,
		"colorB":255,
		"colorG":0,
		"Ubertip":"点击使用学习测试技能b",
		"Tip":"测试技能b【1级】"
	},
	{
		"id":"ad81",
		"_parent":"shea",
		"baseName":"测试技能b",
		"grade":2,
		"abilityId":"ANto",
		"Name":"测试技能b【2级】",
		"Description":"点击使用学习测试技能b",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCriticalStrike.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"Ubertip":"点击使用学习测试技能b",
		"Tip":"测试技能b【2级】"
	},
	{
		"id":"ad82",
		"_parent":"shea",
		"baseName":"测试技能c",
		"grade":1,
		"abilityId":"AOcl",
		"Name":"测试技能c【1级】",
		"Description":"点击使用学习测试技能c",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCriticalStrike.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":255,
		"colorB":0,
		"colorG":255,
		"Ubertip":"点击使用学习测试技能c",
		"Tip":"测试技能c【1级】"
	},
	{
		"id":"ad83",
		"_parent":"shea",
		"baseName":"测试技能c",
		"grade":2,
		"abilityId":"AOmi",
		"Name":"测试技能c【2级】",
		"Description":"点击使用学习测试技能c",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCriticalStrike.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":255,
		"colorB":0,
		"colorG":0,
		"Ubertip":"点击使用学习测试技能c",
		"Tip":"测试技能c【2级】"
	},
	{
		"id":"ad84",
		"_parent":"shea",
		"baseName":"测试技能d",
		"grade":1,
		"abilityId":"AOr2",
		"Name":"测试技能d【1级】",
		"Description":"点击使用学习测试技能d",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCleavingAttack.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":0,
		"colorB":0,
		"colorG":255,
		"Ubertip":"点击使用学习测试技能d",
		"Tip":"测试技能d【1级】"
	},
	{
		"id":"ad85",
		"_parent":"shea",
		"baseName":"测试技能d",
		"grade":2,
		"abilityId":"AOre",
		"Name":"测试技能d【2级】",
		"Description":"点击使用学习测试技能d",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCleavingAttack.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":0,
		"colorB":255,
		"colorG":0,
		"Ubertip":"点击使用学习测试技能d",
		"Tip":"测试技能d【2级】"
	},
	{
		"id":"ad86",
		"_parent":"shea",
		"baseName":"测试技能e",
		"grade":1,
		"abilityId":"AOs2",
		"Name":"测试技能e【1级】",
		"Description":"点击使用学习测试技能e",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCleavingAttack.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"Ubertip":"点击使用学习测试技能e",
		"Tip":"测试技能e【1级】"
	},
	{
		"id":"ad87",
		"_parent":"shea",
		"baseName":"测试技能e",
		"grade":2,
		"abilityId":"AOsf",
		"Name":"测试技能e【2级】",
		"Description":"点击使用学习测试技能e",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCleavingAttack.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":255,
		"colorB":0,
		"colorG":255,
		"Ubertip":"点击使用学习测试技能e",
		"Tip":"测试技能e【2级】"
	},
	{
		"id":"ad88",
		"_parent":"shea",
		"baseName":"测试技能f",
		"grade":1,
		"abilityId":"AOsw",
		"Name":"测试技能f【1级】",
		"Description":"点击使用学习测试技能f",
		"Art":"ReplaceableTextures\\PassiveButtons\\PASBTNCleavingAttack.blp",
		"abilList":"AIha",
		"scale":1,
		"file":"Objects\\InventoryItems\\tome\\tome.mdl",
		"colorR":255,
		"colorB":0,
		"colorG":0,
		"Ubertip":"点击使用学习测试技能f",
		"Tip":"测试技能f【1级】"
	}
]
export const d_技能书学习到QWER栏位 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            技能书学习到QWER栏位.cfg.itemIdAndAbilityIdMap[datum.id] = datum.abilityId;
            GradeUtil.setAbilityTypeGrade(datum.id,datum.grade);
            DataBase.getAbilityTypeSolarData(datum.abilityId).baseName = datum.baseName;
        }
    }
}
