//Generated By Solar Editor

import 开局选择英雄角色 from "state/基础/开局选择英雄角色"
/**
	id = 单位id
	weight = 权重
*/
export type data_type = {
	id?: string
	weight?: number
    [key:string]: any
}

declare global {
    type t_选择单位类型池 = data_type
}

export const data: data_type[] = [
	{
		"id":"Hvsh",
		"weight":1
	}
]
export const d_选择单位类型池 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            开局选择英雄角色.cfg.unitIdWeights[datum.id] = datum.weight
        }
    }
}
