//Generated By Solar Editor
import 单位自动创建系统 from "state/系统/单位自动创建系统";
export const data = [
    {
        "id": "dwzdcjxt001",
        "unitId": "hfoo",
        "owner": 11,
        "loc": {
            "x": 100,
            "y": 0
        },
        "creationTime": 0.01,
        "count": 1,
        "area": 200
    },
    {
        "id": "au01",
        "unitId": "au01",
        "owner": 11,
        "loc": {
            "x": 100,
            "y": 20
        },
        "creationTime": 0.01,
        "count": 1
    }
];
export const d_单位自动创建系统 = data;
//code
export default function () {
    for (let datum of data) {
        if (datum.id) {
            单位自动创建系统.config.push(datum);
        }
    }
}
