//Generated By Solar Editor
import 开局选择英雄角色 from "state/基础/开局选择英雄角色";
export const data = [
    {
        "key_name": "备选项数量",
        "value": 3,
        "#<%1%>#": "    开局选择英雄角色.cfg.optionSize = 3"
    },
    {
        "key_name": "默认可重随次数",
        "value": 1,
        "#<%1%>#": "    开局选择英雄角色.cfg.freeRefreshCount = 1"
    }
];
export const d_开局选择英雄角色 = data;
//code
export default function () {
    开局选择英雄角色.cfg.optionSize = 3;
    开局选择英雄角色.cfg.freeRefreshCount = 1;
}
