//Generated By Solar Editor
import 开局选择英雄角色 from "state/基础/开局选择英雄角色";
export const data = [
    {
        "id": "Ecen",
        "weight": 1
    },
    {
        "id": "Edem",
        "weight": 1
    },
    {
        "id": "Ekee",
        "weight": 1
    },
    {
        "id": "Ekgg",
        "weight": 1
    },
    {
        "id": "Emns",
        "weight": 1
    },
    {
        "id": "Emoo",
        "weight": 1
    },
    {
        "id": "Ewar",
        "weight": 1
    },
    {
        "id": "Hamg",
        "weight": 1
    },
    {
        "id": "Hapm",
        "weight": 1
    },
    {
        "id": "Hart",
        "weight": 1
    },
    {
        "id": "Hblm",
        "weight": 1
    },
    {
        "id": "Hjai",
        "weight": 1
    },
    {
        "id": "Hmbr",
        "weight": 1
    },
    {
        "id": "Hvsh",
        "weight": 1
    },
    {
        "id": "Hvwd",
        "weight": 1
    },
    {
        "id": "Nal2",
        "weight": 1
    },
    {
        "id": "Nbbc",
        "weight": 1
    },
    {
        "id": "Nbrn",
        "weight": 1
    },
    {
        "id": "Nbst",
        "weight": 1
    },
    {
        "id": "Nfir",
        "weight": 1
    },
    {
        "id": "Nmag",
        "weight": 1
    },
    {
        "id": "Nngs",
        "weight": 1
    },
    {
        "id": "Npbm",
        "weight": 1
    },
    {
        "id": "Npld",
        "weight": 1
    },
    {
        "id": "Nrob",
        "weight": 1
    },
    {
        "id": "Nsjs",
        "weight": 1
    },
    {
        "id": "Ocb2",
        "weight": 1
    },
    {
        "id": "Odrt",
        "weight": 1
    }
];
export const d_选择单位类型池 = data;
//code
export default function () {
    for (let datum of data) {
        if (datum.id) {
            开局选择英雄角色.cfg.unitIdWeights[datum.id] = datum.weight;
        }
    }
}
