//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	icon = 图标
	model = 模型
	moveSpeed = 移速
	maxLife = 生命值
	maxMana = 最大魔法值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	flyHeight = 飞行高度
	goldCost = 金币消耗
	describe = 提示说明
	bountyItems = 死亡掉落的物品
	sellItems = 售卖演员物品类型id列表
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	icon?: string
	model?: any
	moveSpeed?: any
	maxLife?: any
	maxMana?: any
	def?: any
	damage?: any
	damageCd?: any
	range?: any
	missileModel?: any
	moveType?: any
	flyHeight?: any
	goldCost?: any
	describe?: any
	bountyItems?: any
	sellItems?: any[]
    [key:string]: any
}

declare global {
    type t_基础单位演员 = data_type
}

export const data: data_type[] = [
	{
		"id":"商店",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"商店",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNSunKey.blp",
		"sellItems":[]
	},
	{
		"id":"小乌龟",
		"class":"基础单位",
		"templateType":"近战单位",
		"name":"小乌龟",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNSunKey.blp",
		"bountyItems":{
			"afac":0.9
		}
	},
	{
		"id":"大螃蟹",
		"class":"基础单位",
		"templateType":"近战力量英雄",
		"name":"大螃蟹",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNSunKey.blp"
	},
	{
		"id":"熊怪",
		"class":"基础单位",
		"templateType":"远程敏捷英雄",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNSunKey.blp"
	},
	{
		"id":"深海巨人",
		"class":"基础单位",
		"templateType":"远程智力英雄",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNSunKey.blp"
	}
]
export const d_基础单位演员 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
