//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	targetType = 目标类型
	 passive = 是否被动技能
	name = 名字
	describe = 提示说明
	icon = 图标
	range = 施放范围
	area = 影响区域
	manaCost = 魔法消耗
	hotKey = 快捷键
	maxCd = 冷却
	x = 按钮x
	y = 按钮y
	attribute = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	targetType?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	range?: number
	area?: number
	manaCost?: number
	hotKey?: string
	maxCd?: number
	x?: number
	y?: number
	attribute?: any
    [key:string]: any
}

declare global {
    type t_技能演员 = data_type
}

export const data: data_type[] = [
	{
		"id":"沟壑",
		"class":"技能",
		"targetType":"点",
		"passive":false,
		"name":"沟壑",
		"describe":"释放技能后，以自身为中心的1200范围内创建时间结界，在区域内的敌对单位，暂停攻击和移动2秒，并每0.2受到智力*0.1的魔法伤害",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNManaShield.blp",
		"range":1000,
		"area":200,
		"manaCost":50,
		"hotKey":"F",
		"maxCd":15,
		"x":0,
		"y":2
	},
	{
		"id":"闪现",
		"class":"技能",
		"targetType":"点",
		"passive":false,
		"name":"闪现",
		"describe":"能瞬间移动一段距离。",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBlink.blp",
		"range":1000,
		"area":0,
		"manaCost":10,
		"hotKey":"D",
		"maxCd":15,
		"x":0,
		"y":2
	}
]
export const d_技能演员 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
