//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	Tip = 提示工具 - 普通
	Ubertip = 提示工具 - 普通 - 扩展
	Art = 图标 - 普通
	Rng = 施法距离
	Area = 影响区域
	Hotkey = 热键 - 普通
	DataA = DataA
	DataB = DataB
	DataC = DataC
	DataD = DataD
	DataE = DataE
	DataF = DataF
	Dur = 持续时间 - 普通
	Cost = 魔法消耗
	Cool = 魔法施放时间间隔
	BuffID = 魔法效果
	HeroDur = 持续时间 - 英雄
	TargetArt = 效果 - 目标
	Researchubertip = 提示工具 - 学习 - 扩展
	SpecialArt = 效果 -特殊
	Researchhotkey = 热键 - 学习
	Researchtip = 提示工具 - 学习
	Animnames = 效果 - 施法动作
	Effectsound = 音效
	ResearchArt = 图标 - 学习
	levels = 等级
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	Tip?: any
	Ubertip?: any
	Art?: string
	Rng?: any
	Area?: any
	Hotkey?: string
	DataA?: any
	DataB?: any
	DataC?: any
	DataD?: any
	DataE?: any
	DataF?: any
	Dur?: any
	Cost?: any
	Cool?: any
	BuffID?: any
	HeroDur?: any
	TargetArt?: string
	Researchubertip?: string
	SpecialArt?: string
	Researchhotkey?: string
	Researchtip?: string
	Animnames?: string
	Effectsound?: string
	ResearchArt?: string
	levels?: number
    [key:string]: any
}

declare global {
    type t_技能 = data_type
}

export const data: data_type[] = [
	{
		"id":"A000",
		"_parent":"AUim",
		"Name":"沟壑",
		"Tip":{
			1:"沟壑|cffffcc00F|rissure - [|cffffcc00等级 1|r]",
			2:"沟壑|cffffcc00F|rissure - [|cffffcc00等级 2|r]",
			3:"沟壑|cffffcc00F|rissure - [|cffffcc00等级 3|r]",
			4:"沟壑|cffffcc00F|rissure - [|cffffcc00等级 4|r]"
		},
		"Ubertip":{
			1:"\"Raigor用图腾撕裂地表，形成巨大的沟壑，8秒内不得通过，造成125点伤害，晕眩1秒。\"",
			2:"\"Raigor用图腾撕裂地表，形成巨大的沟壑，8秒内不得通过，造成175点伤害，晕眩1.25秒。\"",
			3:"\"Raigor用图腾撕裂地表，形成巨大的沟壑，8秒内不得通过，造成225点伤害，晕眩1.5秒。\"",
			4:"\"Raigor用图腾撕裂地表，形成巨大的沟壑，8秒内不得通过，造成275点伤害，晕眩1.75秒。\""
		},
		"Art":"ReplaceableTextures\\CommandButtons\\BTNShockWave.blp",
		"Rng":{
			1:"1200.0",
			2:"1200.0",
			3:"1200.0",
			4:"1200.0"
		},
		"Area":{
			1:"300.0",
			2:"300.0",
			3:"300.0"
		},
		"Hotkey":"F",
		"DataA":{
			1:"1200.0",
			2:"1200.0",
			3:"1200.0",
			4:"1200.0"
		},
		"DataB":{
			1:"0.0",
			2:"0.0",
			3:"0.0",
			4:"0.0"
		},
		"DataC":{
			1:"125.0",
			2:"175.0",
			3:"225.0",
			4:"275.0"
		},
		"DataD":{
			1:"0.0",
			2:"0.0",
			3:"0.0",
			4:"0.0"
		},
		"Dur":{
			1:"1.0",
			2:"1.25",
			3:"1.5",
			4:"1.75"
		},
		"Cost":{
			1:"125",
			2:"140",
			3:"155",
			4:"170"
		},
		"Cool":{
			1:"15.0",
			2:"15.0",
			3:"15.0",
			4:"15.0"
		},
		"BuffID":{
			1:"BPSE",
			2:"BPSE",
			3:"BPSE",
			4:"BPSE"
		},
		"HeroDur":{
			2:"1.25",
			3:"1.5",
			4:"1.75"
		},
		"TargetArt":"Abilities\\Spells\\Other\\Volcano\\VolcanoDeath.mdl",
		"Researchubertip":"\"Raigor用图腾撕裂地表，形成巨大的沟壑，8秒内不得通过，并造成伤害和晕眩。|n施法距离1200，冷却时间15秒。|n|n|cffffcc00等级 1|r - 造成75点的伤害，1秒的眩晕。|n消耗125秒的魔法。|n|cffffcc00等级 2|r - 造成145点的伤害，1.5秒的眩晕。|n消耗140秒的魔法。|n|cffffcc00等级 3|r - 造成210点的伤害，2秒的眩晕。|n消耗155秒的魔法。|n|cffffcc00等级 4|r - 造成320点的伤害，2秒的眩晕。|n消耗170秒的魔法。\"",
		"SpecialArt":"",
		"Researchhotkey":"F",
		"Researchtip":"学习沟壑|cffffcc00F|rissure - [|cffffcc00等级 %d|r]",
		"Animnames":"slam",
		"Effectsound":"",
		"ResearchArt":"ReplaceableTextures\\CommandButtons\\BTNShockWave.blp",
		"levels":4
	}
]
export const d_技能 = data;


//code
export default function(){
}
