//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	Ubertip = 提示工具 - 普通 - 扩展
	Art = 图标 - 普通
	Hotkey = 热键 - 普通
	Buttonpos_1 = 按钮位置 - 普通 (X)
	Buttonpos_2 = 按钮位置 - 普通 (Y)
	Cost = 消耗魔法
	Area = 影响区域
	DataA = DataA
	DataG = DataG
	Dur = 持续时间 - 普通
	BuffID = 魔法效果
	HeroDur = 持续时间 - 英雄
	Animnames = 效果 - 施法动作
	CasterArt = 效果 - 施法者
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	Ubertip?: string
	Art?: string
	Hotkey?: string
	Buttonpos_1?: number
	Buttonpos_2?: number
	Cost?: number
	Area?: number
	DataA?: number
	DataG?: number
	Dur?: number
	BuffID?: string
	HeroDur?: number
	Animnames?: string
	CasterArt?: string
    [key:string]: any
}

declare global {
    type t_显示cd的被动技能 = data_type
}

export const data: data_type[] = [
	{
		"id":"ab01",
		"_parent":"Aroa",
		"Name":"带cd的被动技能",
		"Ubertip":"带cd的被动技能",
		"Art":"ReplaceableTextures\\CommandButtons\\BTNAncestralSpirit.blp",
		"Hotkey":" ",
		"Buttonpos_1":0,
		"Buttonpos_2":2,
		"Cost":0,
		"Area":0.0,
		"DataA":0.0,
		"DataG":-1.0,
		"Dur":0.0,
		"BuffID":" ",
		"HeroDur":0.0,
		"Animnames":" ",
		"CasterArt":" ",
		"Tip":"带cd的被动技能"
	}
]
export const d_显示cd的被动技能 = data;


//code
export default function(){
}
